name: Deploy Python App to Azure WebApp

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub runner OS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gobest'  # Your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # GitHub secret
        package: .
